account_id = "0d13146e53ce108313d59c78906cd900"
name = "template-site"
type = "webpack"
workers_dev = true

site = { bucket = "./public" }
compatibility_date = "2021-12-20"

[env.dev]
workers_dev = false
zone_id = "e6bf1f06148cb143e391370e9edf3aef"
route = "https://ulysseskee.software/*"
