name = "serverless-api"
type = "webpack"
account_id = "0d13146e53ce108313d59c78906cd900"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-12-28"
