name = "flaretools-serverless-api"
type = "webpack"
account_id = "8ca3b5fc5d350c3d41936bc288be236d"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2021-12-28"